[package]
name = "gd32vf103-pac"
version = "0.1.0"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for GD32VF103 chips"
keywords = ["riscv", "gd32", "register", "peripheral"]
license = "ISC"
edition = "2018"

[dependencies]
bare-metal = "0.2.5"
riscv = "0.5.4"
riscv-rt = { version = "0.6.1", optional = true }
vcell = "0.1.2"

[features]
rt = ["riscv-rt"]
